### ISSUE TITLE
JWT error when adding new asset and testing connectivity

### ISSUE THREAD

**Issue by JonathanEJewel** [splunk-soar-connectors/sophosendpointprotection#4]
**Name of the app**
Sophos Endpoint Protection

**Describe the bug**
After inputing our Sophos Client ID and Client Secret, any action we try to take or when we test connectivity we have a 'jwt-token' error come up.

**To Reproduce**
1. Go to 'Apps'
2. Click on 'Configure New Asset' for the App Sophos Endpoint Protection
3. Input asset info and asset settings and then run 'Test Connectivity'

**Expected behavior**
After inputing the correct Client ID and Client Secret we should be able to use the functionality of the app via actions on events and in playbooks.

**Screenshots**
App 'Sophos Endpoint Protection' started successfully (id: 1658440223305) on asset: 'sophos-api'(id: 14)
Loaded action execution configuration
Connecting to the endpoint for test connectivity
Didn't find the JWT token, trying to fetch one.
idType: None
Fetching the JWT token
Hitting the URL for JWT token: https://id.sophos.com/api/v2/oauth2/token
Response in JSON: {'access_token': '[REDACTED]', 'errorCode': 'success', 'expires_in': 3600, 'message': 'OK', 'refresh_token': '[REDACTED]', 'token_type': 'bearer', 'trackingId': '[REDACTED]'}
Return value: True
Saving to state
2 actions failed handle_action exception occurred. Error string: ''jwt-token''

**Splunk SOAR Version (please complete the following information):**
 - Splunk SOAR Version version 5.3.1.84890
 - Deployed from AWS AMI

**Additional Context**
- In a playbook we attempted the list endpoint action and it returned the "jwt-token" error as well.

**Comment by edro15** [comment]
Hi @JonathanEJewel ,

Thanks for opening this issue. Unfortunately I don't have an environment to reproduce what you're reporting. 
However, if you have the chance to modify the code of the app in your environment, please apply the following change and verify whether fixes the error.

```diff
# sophosendpointprotection_consts.py@20,21 
-SOPHOS_JWT_TOKEN = "jwt-token"
+SOPHOS_JWT_TOKEN = "access_token"
```

Hope it helps.

**Comment by edro15** [comment]
Hi @JonathanEJewel ,

Glad to see you closed this issue. However, still wondering... Did you solve the issue? Did the recommended change fix it? 
It would be awesome if you could share more details on that for the whole community. Thanks in advance for sharing.

**Comment by JonathanEJewel** [comment]
Hello, 

Sorry for not commenting earlier!

I redownloaded the "Sophos Endpoint Protection" app and made the changes you listed above. After reuploading the new version to our splunk SOAR deployment we recreated the app and after testing the conectivity it worked!

Thank you for the assistance
